<?php

use Illuminate\Database\Seeder;
use App\CentroDiCosto;

class CDCTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        try {
            DB::table('ta003_cdc')->insert(['c_cdc' => 000, 't_sed' => 'NO CDC']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 10, 't_sed' => 'Ex freccia mov  (vecchia den CDC dico montelupo mov gv)']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 15, 't_sed' => 'sammontana mont. mov. - esselunga fv mov']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 16, 't_sed' => 'pam pontedera gv - pam pontedera gv']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 17, 't_sed' => 'grg / sesto f.no - mov - grg / sesto f.no - mov']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 18, 't_sed' => 'grg / via einstein - mov - grg / via einstein - mov']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 20, 't_sed' => 'trasporto soci - autisti aut']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 21, 't_sed' => 'interno cap /soci - addetti mercato']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 22, 't_sed' => 'zona market pistoia - zona market pistoia']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 24, 't_sed' => 'STRUTTURA FRIGO B4/SOCI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 27, 't_sed' => 'conad mont fv/soci - conad montopoli f. & v.']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 28, 't_sed' => 'fruttital/soci - cepre cep']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 29, 't_sed' => 'ess. fr. e verd./soci - esselunga f&v ess']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 30, 't_sed' => 'esselunga gv /soci - esselun.notte n.e.']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 300, 't_sed' => 'A.O.U.P. VERDE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 301, 't_sed' => 'AAMPS FONTI DEL CORALLO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 304, 't_sed' => 'BELVEDERE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 307, 't_sed' => 'CIS']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 309, 't_sed' => 'COMUNE BIENTINA spazzamento']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 31, 't_sed' => 'penny altopascio / soci - penny market altopascio']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 314, 't_sed' => 'COMUNE CASCINA SPAZZAMENTO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 315, 't_sed' => 'COMUNE CASTELFRANCO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 318, 't_sed' => 'COMUNE PONTEDERA SPAZZAMENTO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 319, 't_sed' => 'COMUNE SAN TEODORO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 321, 't_sed' => 'COOPTIMA SERVICE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 322, 't_sed' => 'CTF CARTA E CARTONE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 323, 't_sed' => 'ECOACCIAI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 324, 't_sed' => 'ECOFOR DISCARICA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 325, 't_sed' => 'ECOFOR DISCARICA VERDE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 326, 't_sed' => 'ESA ISOLA D\'ELBA PAP']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 327, 't_sed' => 'EUROAMBIENTE GLOBAL SERVICE VE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 329, 't_sed' => 'GE.SAT']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 330, 't_sed' => 'GEOFOR  PAP PONTEDERA 1°LOTTO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 331, 't_sed' => 'GEOFOR BIG-BAGS']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 332, 't_sed' => 'GEOFOR CALCI PAP']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 334, 't_sed' => 'GEOFOR CASCINA PIAZZOLE ']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 335, 't_sed' => 'GEOFOR LARI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 337, 't_sed' => 'GEOFOR MERCATI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 338, 't_sed' => 'GEOFOR PAP BIENTINA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 339, 't_sed' => 'GEOFOR PAP CASCINA ']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 34, 't_sed' => 'cpr lastra/soci - signa']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 340, 't_sed' => 'GEOFOR PAP CASTELFRANCO DI SOT']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 341, 't_sed' => 'GEOFOR PAP E RSU BUTI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 342, 't_sed' => 'GEOFOR PAP LARI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 344, 't_sed' => 'GEOFOR PAP PONTEDERA CENTRO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 345, 't_sed' => 'GEOFOR PAP PONTEDERA CHIESINO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 346, 't_sed' => 'GEOFOR PAP PONTEDERA FRAZIONI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 348, 't_sed' => 'GEOFOR PAP S.GIULIANO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 349, 't_sed' => 'GEOFOR PAP VECCHIANO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 35, 't_sed' => 'struttura livorno/soci - agenz.livorno liv']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 350, 't_sed' => 'GEOFOR PISA PAP CARTA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 351, 't_sed' => 'GEOFOR PONTEDERA PIAZZOLE ']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 356, 't_sed' => 'IREN-PARMA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 359, 't_sed' => 'PECCIOLI SERVICE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 360, 't_sed' => 'QUADRIFOGLIO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 361, 't_sed' => 'QUADRIFOGLIO RACCOLTA INGOMBRA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 362, 't_sed' => 'QUADRIFOGLIO RACCOLTA RSU E MM']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 364, 't_sed' => 'RIFIUTI SANITARI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 366, 't_sed' => 'UNIONE DI COMUNI MONTANA LUNIG']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 37, 't_sed' => 'pam pontedera fv - pam pontedera fv']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 370, 't_sed' => 'FOND. TOSCANA G. MONASTERIO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 376, 't_sed' => 'COMUNE CASCINA TAGLIO ERBA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 38, 't_sed' => 'struttura firenze/soci - strutt.firenze str']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 380, 't_sed' => 'CTF BILICI E WF']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 381, 't_sed' => 'CTF SCARRABILI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 382, 't_sed' => 'CTF MULTIMATERIALE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 39, 't_sed' => 'o/m off.mezzi/soci - offic. mezzi off']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 390, 't_sed' => 'GEOFOR INCENERITORE TECNICA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 391, 't_sed' => 'GEOFOR PONTEDERA PAP II LOTTO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 392, 't_sed' => 'GEOFOR S.GIULIANO ASS. CAMPANE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 395, 't_sed' => 'GEOFOR VECCHIANO ASS. CAMPANE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 397, 't_sed' => 'QUADRIFOGLIO VERDE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 40, 't_sed' => 'o/a automezzi/soci - off. automezzi off']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 41, 't_sed' => 'cft varie/soci - cft varie']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 43, 't_sed' => 'pasticceria esselunga ept - pasticc. esselunga ept']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 45, 't_sed' => 'vivobio - vivobio']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 46, 't_sed' => 'giotto/soci - giotto']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 47, 't_sed' => 'metro firenze/soci - metro firenze']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 49, 't_sed' => 'pam pontedera ittico - pam pontedera ittico']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 50, 't_sed' => 'unicoop fi gv - unicoop  scandicci']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 502, 't_sed' => 'ACQUE INDUSTRIALI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 504, 't_sed' => 'ACQUE S.P.A']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 505, 't_sed' => 'PC SYSTEM']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 507, 't_sed' => 'ADF - AEROPORTO DI FIRENZE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 510, 't_sed' => 'ARCA ALLESTIMENTI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 511, 't_sed' => 'ARCA REALIZZAZIONE PONTEGGI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 512, 't_sed' => 'ASSOCIAZIONE CIMITERO PUGNANO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 513, 't_sed' => 'ATL']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 514, 't_sed' => 'AUSTRIA MS']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 515, 't_sed' => 'AUTOSCUOLA VALDISERCHIO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 517, 't_sed' => 'BARGAGNA LEONARDO pulizia Aren']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 518, 't_sed' => 'C.U.S PISA SERVIZI VARI FACILE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 523, 't_sed' => 'CEREALIA PANE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 525, 't_sed' => 'CILP PORTIERATO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 526, 't_sed' => 'CILP PULIZIE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 527, 't_sed' => 'CILP SERVIZI EXTRA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 528, 't_sed' => 'CLIENTI VARI FRANGIONI - PAMPA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 529, 't_sed' => 'GESTE SOMMINISTRAZIONE PASTI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 531, 't_sed' => 'COMUNE CALCINAIA - MANUTENZION']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 532, 't_sed' => 'COMUNE CALCINAIA - OPERAZIONI ']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 533, 't_sed' => 'COMUNE CASCINA CIMITERI - MANU']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 534, 't_sed' => 'COMUNE CASCINA CIMITERI - OPER']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 535, 't_sed' => 'COMUNE CASCINA MANUT. SCUOLE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 536, 't_sed' => 'COMUNE COLLESALVETTI OPERAZION']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 538, 't_sed' => 'UNIONE VALDERA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 539, 't_sed' => 'CILP MANUTENZIONI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 54, 't_sed' => 'unicoop fi ittico - upe']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 540, 't_sed' => 'COMUNE SMAM - MANUTENZIONI CIM']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 541, 't_sed' => 'COMUNE SMAM - OPERAZIONI CIMIT']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 542, 't_sed' => 'COMUNE VECCHIANO - MANUTENZION']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 543, 't_sed' => 'COMUNE VICOPISANO - MANUTENZIO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 544, 't_sed' => 'COMUNE VICOPISANO - OPERAZIONI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 545, 't_sed' => 'COMUNE VINCI CIMITERI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 546, 't_sed' => 'CONSI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 550, 't_sed' => 'CPT PISA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 551, 't_sed' => 'CPT SAN MINIATO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 555, 't_sed' => 'ECOFOR PULIZIE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 556, 't_sed' => 'EDILCOSTRUZIONI PULIZIE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 56, 't_sed' => 'cpr cast del lago - cpr  cast. lago']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 560, 't_sed' => 'EXENTRICA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 562, 't_sed' => 'FLORA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 569, 't_sed' => 'GALILEO CONSULTING PONSACCO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 570, 't_sed' => 'GALILEO CONSULTING PONTEDERA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 572, 't_sed' => 'GEOFOR - PISA PULIZIE SERVIZI ']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 573, 't_sed' => 'GEOFOR INCENERITORE PULIZIE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 574, 't_sed' => 'GEOFOR PISA BOX CONTAINER']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 582, 't_sed' => 'GUSTOLANDIA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 589, 't_sed' => 'IL GIRASOLE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 59, 't_sed' => 'unicoop pontedera /soci - unicoop fi pontedera']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 597, 't_sed' => 'ITALIAONLINE PULIZIE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 60, 't_sed' => 'CSC MOV']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 605, 't_sed' => 'HOTEL ARMONIA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 606, 't_sed' => 'MISERICORDIA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 61, 't_sed' => 'coop italia macrolotto - coop italia macrolotto']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 611, 't_sed' => 'MOSAICO MDA RSA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 613, 't_sed' => 'COMUNE PONTEDERA PULIZIE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 615, 't_sed' => 'P. ASSISTENZA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 623, 't_sed' => 'POLO TECNOLOGICO PULIZIE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 624, 't_sed' => 'PRATICELLI PORTIERATO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 625, 't_sed' => 'APPAROUND']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 627, 't_sed' => 'PROVINCIA PISA PORTIERATO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 630, 't_sed' => 'QUADRIFOGLIO PULIZIE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 631, 't_sed' => 'REMAGGI PULIZIE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 634, 't_sed' => 'SANDRI REARTO """"DE""""']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 635, 't_sed' => 'SANDRI REPARTI """"AB+E1+E""""']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 636, 't_sed' => 'SANDRI REPARTO """"E2""""']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 637, 't_sed' => 'SANDRI REPARTO """"J""""']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 638, 't_sed' => 'SANDRI SANIFICAZIONE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 64, 't_sed' => 'pam no food - pam no food']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 640, 't_sed' => 'SAT CARGO VILLAGE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 641, 't_sed' => 'SAT HANDLING']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 643, 't_sed' => 'SAT MANUTENZIONI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 644, 't_sed' => 'SAT PULIZIE ORDINARIA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 645, 't_sed' => 'SAT SALA VIP']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 646, 't_sed' => 'SCUOLA NORMALE RISTORAZIONE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 65, 't_sed' => 'eurogroup oppeano - eurogroup oppeano']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 651, 't_sed' => 'SO.GE.SI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 652, 't_sed' => 'SOGEFARM']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 66, 't_sed' => 'sma siena/soci - sma siena']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 661, 't_sed' => 'UNICOOP CENTRO FRESCHI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 662, 't_sed' => 'UNICOOP CENTRO FRESCHI - LAVAG']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 664, 't_sed' => 'VALDARNO']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 677, 't_sed' => 'C.S.C.']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 68, 't_sed' => 'esselunga prato - esselunga prato']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 681, 't_sed' => 'CPL']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 69, 't_sed' => 'cft ittico deposito (S.Maria Assunta)']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 693, 't_sed' => 'SANDRI SOSTITUZIONI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 70, 't_sed' => 'casei gerola soci - cpr casei gerola']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 700, 't_sed' => 'TOSCANA ENERGIA G.S.PULIZIE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 703, 't_sed' => 'FARMAPIANA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 71, 't_sed' => 'pam pontedera las - pam pontedera las']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 72, 't_sed' => 'pam pontedera carni - pam pontedera carni']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 73, 't_sed' => 'coop italia bruschi - coop italia bruschi']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 74, 't_sed' => 'EX CLSC MOV']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 76, 't_sed' => 'sogegross - mov - sogegross - mov']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 78, 't_sed' => 'unicoop -  ariccia - unicoop - ariccia']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 79, 't_sed' => 'cft ittico negozio (S.Maria Assunta)']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 80, 't_sed' => 'unicoop  ml g.v. - unicoop  pontedera']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 801, 't_sed' => 'A.Daveti']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 802, 't_sed' => 'A.Solimeno']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 805, 't_sed' => 'E.Appella']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 806, 't_sed' => 'F.Antonelli']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 807, 't_sed' => 'F.Bianchi']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 808, 't_sed' => 'G.Ginetti']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 809, 't_sed' => 'M.Barbieri']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 81, 't_sed' => 'unicoop  ml s.l. - unicoop pontedera las']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 810, 't_sed' => 'M.Domenici']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 811, 't_sed' => 'M.Vezzi']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 812, 't_sed' => 'S.Giovannetti']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 813, 't_sed' => 'A.Benvenuti']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 815, 't_sed' => 'A.Salama']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 816, 't_sed' => 'G.Montemarani']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 817, 't_sed' => 'I.Frangioni']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 818, 't_sed' => 'L.Frangioni']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 819, 't_sed' => 'R.Gori']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 82, 't_sed' => 'unicoop  ml c.b. - unicoop pontedera cb']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 820, 't_sed' => 'T.Baglini']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 822, 't_sed' => 'T.Gelli']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 823, 't_sed' => 'C. Rossi']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 824, 't_sed' => 'R. Oragano']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 83, 't_sed' => 'unicoop pontedera confez. - unicoop pontedera confez.']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 85, 't_sed' => 'esselunga las - esselunga las']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 86, 't_sed' => 'estav - estav']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 88, 't_sed' => 'centro carni di qualita\' - centro carni di qualita\'']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 893, 't_sed' => 'Comuni di staff Pontedera']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 900, 't_sed' => 'UB LOGISTICA INTEGRATA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 903, 't_sed' => 'UB IMMOBILIARE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 904, 't_sed' => 'DIREZIONE STRATEGICA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 906, 't_sed' => 'AFFARI GENERALI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 907, 't_sed' => 'GARANZIE DI SISTEMA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 908, 't_sed' => 'CONTROLLO DI GESTIONE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 909, 't_sed' => 'RELAZIONI CORPO SOCIALE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 910, 't_sed' => 'ACQUISTI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 911, 't_sed' => 'GESTIONE DEL PERSONALE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 912, 't_sed' => 'AMMINISTRAZIONE DEL PERSONALE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 913, 't_sed' => 'SISTEMI INFORMATIVI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 914, 't_sed' => 'TESORERIA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 915, 't_sed' => 'AMMINISTRAZIONE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 916, 't_sed' => 'MANUTENZIONI']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 951, 't_sed' => 'UB AMBIENTE PONTEDERA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 952, 't_sed' => 'UB FACILITY PONTEDERA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 954, 't_sed' => 'DIREZIONE STRATEGICA PONTEDERA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 955, 't_sed' => 'GARE PONTEDERA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 956, 't_sed' => 'AFFARI GENERALI PONTEDERA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 957, 't_sed' => 'GARANZIE DI SISTEMA PONTEDERA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 958, 't_sed' => 'CONTROLLO DI GESTIONE PONTEDER']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 960, 't_sed' => 'ACQUISTI PONTEDERA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 961, 't_sed' => 'GESTIONE DEL PERSONALE PONTEDE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 962, 't_sed' => 'AMMINISTR . DEL PERSONALE PONTE']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 963, 't_sed' => 'SISTEMI INFORMATIVI PONTEDERA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 964, 't_sed' => 'TESORERIA PONTEDERA']);
            DB::table('ta003_cdc')->insert(['c_cdc' => 965, 't_sed' => 'AMMINISTRAZIONE PONTEDERA']);
        } catch (QueryException  $e) {
            var_dump($e->errorInfo);
        }

    }
}
